In [1]:
#import the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt # a plotting library for Python and NumPy (readily customizable)
import seaborn as sns # Another plotting library for Python (fewer syntax, excellent default themes, behind the scenes, it uses matplotlib)
import time

# Step 1 : Read the Data!

In [2]:
#give path of the source-file and store that path in a variable named census
from google.colab import drive
drive.mount('/content/drive')

census = '/content/drive/MyDrive/makeSenseOfCensus.csv'


Mounted at /content/drive


# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [3]:
data = np.genfromtxt(census, delimiter ="," , skip_header =1)
print("\nData:\n\n ", data)


Data:

  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [4]:
#print the type of data
print("Type of data:\n\n\n\n\n", type(data))

Type of data:




 <class 'numpy.ndarray'>


# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [5]:
new_record = [[50,9,4,1,0,0,40,0]]


## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [6]:
np.concatenate((data,new_record), axis=0)

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [7]:
#display after appending the new record at the end of the array.
new_record_added = np.concatenate((data,new_record), axis=0)
print(new_record_added)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [8]:
age = data[:, 0]
print("Age:\n\n", age)

Age:

 [39. 50. 38. 53. 28. 37. 49. 52. 31. 42. 37. 30. 23. 32. 40. 34. 25. 32.
 38. 43. 40. 54. 35. 43. 59. 56. 19. 54. 39. 49. 23. 20. 45. 30. 22. 48.
 21. 19. 31. 48. 31. 53. 24. 49. 25. 57. 53. 44. 41. 29. 25. 18. 47. 50.
 47. 43. 46. 35. 41. 30. 30. 32. 48. 42. 29. 36. 28. 53. 49. 25. 19. 31.
 29. 23. 79. 27. 40. 67. 18. 31. 18. 52. 46. 59. 44. 53. 49. 33. 30. 43.
 57. 37. 28. 30. 34. 29. 48. 37. 48. 32. 76. 44. 47. 20. 29. 32. 17. 30.
 31. 42. 24. 38. 56. 28. 36. 53. 56. 49. 55. 22. 21. 40. 30. 29. 19. 47.
 20. 31. 35. 39. 28. 24. 38. 37. 46. 38. 43. 27. 20. 49. 61. 27. 19. 45.
 70. 31. 22. 36. 64. 43. 47. 34. 33. 21. 52. 48. 23. 71. 29. 42. 68. 25.
 44. 28. 45. 36. 39. 46. 18. 66. 27. 28. 51. 27. 28. 27. 21. 34. 18. 33.
 44. 43. 30. 40. 37. 34. 41. 53. 31. 58. 38. 24. 41. 47. 41. 23. 36. 40.
 35. 24. 26. 19. 51. 42. 37. 18. 36. 35. 58. 17. 44. 37. 35. 60. 54. 37.
 50. 38. 45. 25. 31. 64. 90. 54. 53. 18. 60. 66. 75. 65. 35. 41. 25. 33.
 28. 59. 40. 41. 38. 23. 40. 41. 24. 20. 38.

Find the max age and store it in a variable called 'max_age'.



In [9]:
#print the max_age
max_age = np.max(age)
print("Maximum age:\n\n", max_age)

Maximum age:

 90.0


Find the min age and store it in a variable called 'min_age'.

In [10]:
#print the min_age
min_age = np.min(age)
print("Minimum age:\n\n", min_age)

Minimum age:

 17.0


Find the mean of the age and store it in a variable called 'age_mean'.

In [11]:
#print the age_mean
age_mean = np.mean(age)
print("Mean of ages:\n\n", age_mean)

Mean of ages:

 38.051


Find the standard deviation of the age and store it in a variable called 'age_std'

In [12]:
#print the
age_std = np.std(age)
print("Standard deviation of ages:\n\n", age_std)

Standard deviation of ages:

 13.342803266180612


# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [13]:
#np.set_printoptions(suppress=True)
race_0 = data[data[:, 2] == 0]
race_1 = data[data[:, 2] == 1]
race_2 = data[data[:, 2] == 2]
race_3 = data[data[:, 2] == 3]
race_4 = data[data[:, 2] == 4]

# Print the subsets to verify
print("Race 0 subset:\n", race_0)
print("Race 1 subset:\n", race_1)
print("Race 2 subset:\n", race_2)
print("Race 3 subset:\n", race_3)
print("Race 4 subset:\n", race_4)

Race 0 subset:
 [[34.  4.  0.  1.  0.  0. 45.  0.]
 [35. 10.  0.  0.  0.  0. 40.  0.]
 [60.  6.  0.  0.  0.  0. 10.  0.]
 [51.  9.  0.  1.  0.  0. 40.  0.]
 [25. 10.  0.  0.  0.  0. 20.  0.]
 [20.  9.  0.  1.  0.  0. 48.  0.]
 [23. 10.  0.  0.  0.  0. 25.  0.]
 [29.  9.  0.  1.  0.  0. 40.  0.]
 [27. 12.  0.  1.  0.  0. 40.  0.]
 [31. 12.  0.  0.  0.  0. 40.  0.]]
Race 1 subset:
 [[3.000e+01 1.300e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [4.000e+01 1.100e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [5.400e+01 1.000e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 6.000e+01
  1.000e+00]
 [3.000e+01 9.000e+00 1.000e+00 0.000e+00 0.000e+00 1.573e+03 3.500e+01
  0.000e+00]
 [4.900e+01 1.000e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [3.300e+01 1.300e+01 1.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [4.400e+01 1.400e+01 1.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [2.800e+01 9.000e+00 

Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [14]:
#len_0
len_0 = len(race_0)
print(len_0)

10


In [15]:
#len_1
len_1 = len(race_1)
print(len_1)

27


In [16]:
#len_2
len_2 = len(race_2)
print(len_2)

110


In [17]:
#len_3
len_3 = len(race_3)
print(len_3)

6


In [18]:
#len_4
len_4 = len(race_4)
print(len_4)

847


Find out which is the race with the minimum no. of citizens

In [19]:
races_name = ['Race:0', 'Race:1', 'Race:2', 'Race:3', 'Race:4']
races_length = [len_0, len_1, len_2, len_3, len_4]
race_minimum_citizens = np.argmin(races_length)
min_race = races_name[race_minimum_citizens]
print(f"Race with minimum citizens is {min_race}")


Race with minimum citizens is Race:3


Find out which is the race with the maximum no. of citizens

In [20]:
race_maximum_citizens = np.argmax(races_length)
min_race = races_name[race_maximum_citizens]
print(f"Race with maximum citizens is {min_race}")

Race with maximum citizens is Race:4


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [21]:
race_length_list = [len_0, len_1, len_2, len_3, len_4]
minority_race = np.min(race_length_list)
minority_race

6

Store the number associated with the majority race in a variable called 'majority_race'(For eg: if "len(race_5)" is the maximum, store 5 in 'majority_race' because that is the index of the race having the maximum no. of citizens )

In [22]:
race_length_list = [len_0, len_1, len_2, len_3, len_4]
majority_race = np.max(race_length_list)
majority_race

847

# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [23]:
#from age column, filter out age data > 60
senior_citizens = data[(data[:, 0] > 60) & (data[:, 6] <= 25)]

print("Senior Citizens:", senior_citizens)

Senior Citizens: [[7.900e+01 1.000e+01 4.000e+00 1.000e+00 0.000e+00 0.000e+00 2.000e+01
  0.000e+00]
 [6.700e+01 6.000e+00 4.000e+00 1.000e+00 0.000e+00 0.000e+00 2.000e+00
  0.000e+00]
 [7.100e+01 1.000e+01 2.000e+00 1.000e+00 0.000e+00 1.816e+03 2.000e+00
  0.000e+00]
 [6.800e+01 2.000e+00 4.000e+00 0.000e+00 0.000e+00 0.000e+00 2.000e+01
  0.000e+00]
 [6.600e+01 1.100e+01 4.000e+00 0.000e+00 0.000e+00 0.000e+00 2.000e+01
  0.000e+00]
 [7.500e+01 1.100e+01 4.000e+00 0.000e+00 0.000e+00 0.000e+00 2.000e+01
  0.000e+00]
 [6.500e+01 9.000e+00 4.000e+00 1.000e+00 0.000e+00 0.000e+00 1.600e+01
  0.000e+00]
 [6.200e+01 9.000e+00 4.000e+00 0.000e+00 0.000e+00 0.000e+00 2.400e+01
  0.000e+00]
 [7.600e+01 1.400e+01 4.000e+00 1.000e+00 0.000e+00 0.000e+00 1.000e+01
  0.000e+00]
 [6.700e+01 7.000e+00 4.000e+00 1.000e+00 0.000e+00 0.000e+00 8.000e+00
  0.000e+00]
 [8.000e+01 9.000e+00 4.000e+00 1.000e+00 0.000e+00 0.000e+00 2.400e+01
  0.000e+00]
 [6.700e+01 1.100e+01 4.000e+00 0.000e+00 0.000e

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [24]:
working_hours_sum = senior_citizens[:, 6].sum()
print(working_hours_sum)

367.0


c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [25]:
senior_citizens_len = len(senior_citizens)
print(senior_citizens_len)

24


d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [26]:
avg_working_hours = working_hours_sum / senior_citizens_len
avg_working_hours

15.291666666666666

e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [ ]:
print(avg_working_hours)

15.291666666666666


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [28]:
high = data[data[:,1] > 10]
high
low = data[data[:, 1] <= 10]
low

array([[38.,  9.,  4., ...,  0., 40.,  0.],
       [53.,  7.,  2., ...,  0., 40.,  0.],
       [49.,  5.,  2., ...,  0., 16.,  0.],
       ...,
       [35.,  9.,  4., ...,  0., 45.,  0.],
       [56.,  9.,  4., ...,  0., 55.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.]])

Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [31]:
avg_pay_high = np.mean(high[:, 7])
print(f"Average Pay for Higher Educated People {avg_pay_high}")


Average Pay for Higher Educated People 0.42813455657492355


In [32]:
avg_pay_low = np.mean(low[:, 7])
print(f"Average Pay for Lower Educated People {avg_pay_low}")

Average Pay for Lower Educated People 0.13670133729569092
