# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

In [1]:
import numpy as np
# code here (you may create an array of your own choice)

a = np.arange(10.0,80.0,2.5)
print(a)

[10.  12.5 15.  17.5 20.  22.5 25.  27.5 30.  32.5 35.  37.5 40.  42.5
 45.  47.5 50.  52.5 55.  57.5 60.  62.5 65.  67.5 70.  72.5 75.  77.5]


2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

In [ ]:
# code here (you may create an array of your choice of size)
zero_array = np.zeros((2,3), dtype='float64')
one_array = np.ones((2,3), dtype='float64')
print(zero_array)
print(one_array)

3.Generate an n by n identity array. The default dtype is float64.

In [ ]:
# code here (you may create an array of your choice of size)
a = np.identity(3)
print(a)
print(a.dtype)

4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

In [2]:
# code here (use the array created in Question 1 for this)
max_val = a.max()
print("Max:", max_val)

# Min value
min_val = a.min()
print("Min:", min_val)

# Standard Deviation
std_val = a.std()
print("Standard Deviation:", std_val)

# Mean value
mean_val = a.mean()
print("Mean:", mean_val)

# Variance
var_val = a.var()
print("Variance:", var_val)

# Index of the maximum value
argmax_val = a.argmax()
print("Index of max value:", argmax_val)

# Linspace example
arr_linspace = np.linspace(10.0, 80.0, 5)
print("Linspace Array:\n", arr_linspace)

# Fill the array with a specific value
a.fill(25.0)
print("Array after fill:\n", a)

# Reset the array and create a new full array
a = np.arange(10.0, 80.0, 2.5)
full_array = np.full(a.shape, 15.0)
print("Full Array:\n", full_array)

Max: 77.5
Min: 10.0
Standard Deviation: 20.19436802675439
Mean: 43.75
Variance: 407.8125
Index of max value: 27
Linspace Array:
 [10.  27.5 45.  62.5 80. ]
Array after fill:
 [25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25.
 25. 25. 25. 25. 25. 25. 25. 25. 25. 25.]
Full Array:
 [15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]


5. Create the array below with a = np.arange(-15, 15).reshape(5, 6) ** 2

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

In [4]:
import numpy as np

# Step 1: Create the array and convert it to float to handle NaN values
a = np.arange(-15, 15).reshape(5, 6).astype(float) ** 2
print("Original Array 'a':\n", a)

# Reduction operations
mean_a = a.mean()
sum_a = a.sum()
std_a = a.std()
var_a = a.var()

print("Mean of 'a':", mean_a)
print("Sum of 'a':", sum_a)
print("Standard Deviation of 'a':", std_a)
print("Variance of 'a':", var_a)

# Reduction operations with axis
col_sum = a.sum(axis=0)
row_mean = a.mean(axis=1)
print("Column-wise sum of 'a':\n", col_sum)
print("Row-wise mean of 'a':\n", row_mean)

# Step 2: Introducing NaN values
a[2, 3] = np.nan
a[4, 5] = np.nan
print("Array 'a' with missing values:\n", a)

# Handling missing values using nanmean and nansum
nanmean_a = np.nanmean(a)
nansum_a = np.nansum(a)
print("Mean ignoring NaN:", nanmean_a)
print("Sum ignoring NaN:", nansum_a)


Original Array 'a':
 [[225. 196. 169. 144. 121. 100.]
 [ 81.  64.  49.  36.  25.  16.]
 [  9.   4.   1.   0.   1.   4.]
 [  9.  16.  25.  36.  49.  64.]
 [ 81. 100. 121. 144. 169. 196.]]
Mean of 'a': 75.16666666666667
Sum of 'a': 2255.0
Standard Deviation of 'a': 67.45323482894567
Variance of 'a': 4549.938888888889
Column-wise sum of 'a':
 [405. 380. 365. 360. 365. 380.]
Row-wise mean of 'a':
 [159.16666667  45.16666667   3.16666667  33.16666667 135.16666667]
Array 'a' with missing values:
 [[225. 196. 169. 144. 121. 100.]
 [ 81.  64.  49.  36.  25.  16.]
 [  9.   4.   1.  nan   1.   4.]
 [  9.  16.  25.  36.  49.  64.]
 [ 81. 100. 121. 144. 169.  nan]]
Mean ignoring NaN: 73.53571428571429
Sum ignoring NaN: 2059.0


6.Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum

In [5]:
# code here and display all 3 values appropriately. You MUST NOT choose an array of your own choice.
a = np.arange(-15, 15).reshape(5, 6) ** 2
print("Array 'a':\n", a)

# Maximum of each row
row_max = a.max(axis=1)
print("Maximum of each row:\n", row_max)

# Mean of each column
col_mean = a.mean(axis=0)
print("Mean of each column:\n", col_mean)

# Position of the overall minimum value
min_pos = np.unravel_index(a.argmin(), a.shape)
print("Position of the overall minimum value:", min_pos)

Array 'a':
 [[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]
Maximum of each row:
 [225  81   9  64 196]
Mean of each column:
 [81. 76. 73. 72. 73. 76.]
Position of the overall minimum value: (2, 3)


# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [6]:
#code here # Create 2 arrays A and B with dim (5,4) and (5,) respectively, apply addition and subtraction.
A = np.random.randint(1, 10, (5, 4))
B = np.random.randint(1, 10, (5,))

print("Array A:\n", A)
print("Array B:\n", B)

# Apply addition and subtraction
addition_result = A + B[:, np.newaxis]
subtraction_result = A - B[:, np.newaxis]

print("Result of A + B:\n", addition_result)
print("Result of A - B:\n", subtraction_result)

Array A:
 [[3 2 2 1]
 [6 1 1 1]
 [4 6 9 1]
 [5 3 5 7]
 [7 9 8 7]]
Array B:
 [1 6 5 9 7]
Result of A + B:
 [[ 4  3  3  2]
 [12  7  7  7]
 [ 9 11 14  6]
 [14 12 14 16]
 [14 16 15 14]]
Result of A - B:
 [[ 2  1  1  0]
 [ 0 -5 -5 -5]
 [-1  1  4 -4]
 [-4 -6 -4 -2]
 [ 0  2  1  0]]


1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [7]:
# Answer here (use both of these functions on an array of your own choice)
a = np.array([1, 2, 3, 4, 5])
print("Original Array 'a':", a)

np_reduced_sum = np.add.reduce(a)
print("Using np.add.reduce for sum:", np_reduced_sum)

accumulated_sum = np.add.accumulate(a)
print("Accumulated Sum of 'a':", accumulated_sum)

Original Array 'a': [1 2 3 4 5]
Using np.add.reduce for sum: 15
Accumulated Sum of 'a': [ 1  3  6 10 15]


### We will work with the following array:

In [9]:
a = np.arange(25).reshape(5, 5)
a
#moving forward, you must use this array for the operations

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Use slicing only to select 3rd and last row along with 2nd and last columns

In [10]:
# Answer here
result = a[[2, -1], :][:, [1, -1]]

print("Resulting sliced array:\n", result)

Resulting sliced array:
 [[11 14]
 [21 24]]


# Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [11]:
# Answer here
sub_array = a[0::2, 2:4]

print("Extracted sub-array:\n", sub_array)

Extracted sub-array:
 [[ 2  3]
 [12 13]
 [22 23]]


# Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [13]:
# Answer here
sub_array = a[[1, 3, 4], 1:5:2]

print("Extracted sub-array:\n", sub_array)

Extracted sub-array:
 [[ 6  8]
 [16 18]
 [21 23]]


# Change the values 1, 10, 19 and 22 in the array to -2

In [14]:
# Answer
values_to_change = [1, 10, 19, 22]

for value in values_to_change:
    a[a == value] = -2

print("Updated array:\n", a)

Updated array:
 [[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


# Repeat above using boolean indexing

In [15]:
# Answer here
values_to_change = [1, 10, 19, 22]

a[(a == 1) | (a == 10) | (a == 19) | (a == 22)] = -2

print("Updated array:\n", a)

Updated array:
 [[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


# Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [18]:
# Answer here
rows = [0, 2, 3]
sub_array = a[rows][:, [0, 3]]

print("Extracted sub-array:\n", sub_array)

Extracted sub-array:
 [[ 0  3]
 [-2 13]
 [15 18]]


# Calculating the sum, min and max of all diagonal values

In [19]:
# Answer here
diagonal_values = np.diagonal(a)

# Calculate sum, min, and max of diagonal values
diagonal_sum = np.sum(diagonal_values)
diagonal_min = np.min(diagonal_values)
diagonal_max = np.max(diagonal_values)

print("Diagonal Values:", diagonal_values)
print("Sum of Diagonal Values:", diagonal_sum)
print("Minimum of Diagonal Values:", diagonal_min)
print("Maximum of Diagonal Values:", diagonal_max)

Diagonal Values: [ 0  6 12 18 24]
Sum of Diagonal Values: 60
Minimum of Diagonal Values: 0
Maximum of Diagonal Values: 24


# Calculate the sum of differences between the 2nd row and 2nd last column

In [20]:
# Answer here
second_row = a[1]
second_last_column = a[:, -2]

# Calculate the differences
differences = second_row - second_last_column

# Calculate the sum of differences
sum_of_differences = np.sum(differences)

print("Second Row:", second_row)
print("Second Last Column:", second_last_column)
print("Differences:", differences)
print("Sum of Differences:", sum_of_differences)

Second Row: [5 6 7 8 9]
Second Last Column: [ 3  8 13 18 23]
Differences: [  2  -2  -6 -10 -14]
Sum of Differences: -30


# Create a new array that is the sum of even rows and odd rows

In [21]:
# Answer here
even_rows = a[::2]
odd_rows = a[1::2]

# Calculate the sum of even rows and odd rows
sum_even_rows = np.sum(even_rows, axis=0)
sum_odd_rows = np.sum(odd_rows, axis=0)

new_array = np.array([sum_even_rows, sum_odd_rows])

print("Even Rows:\n", even_rows)
print("Odd Rows:\n", odd_rows)
print("Sum of Even Rows:", sum_even_rows)
print("Sum of Odd Rows:", sum_odd_rows)
print("New Array (Sum of Even and Odd Rows):\n", new_array)

Even Rows:
 [[ 0 -2  2  3  4]
 [-2 11 12 13 14]
 [20 21 -2 23 24]]
Odd Rows:
 [[ 5  6  7  8  9]
 [15 16 17 18 -2]]
Sum of Even Rows: [18 30 12 39 42]
Sum of Odd Rows: [20 22 24 26  7]
New Array (Sum of Even and Odd Rows):
 [[18 30 12 39 42]
 [20 22 24 26  7]]


## You are done. Good job!