In [2]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [4]:
# Answer Here
array_3d = np.arange(24).reshape(2,3,4)
print(array_3d)
print(array_3d.sum())

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
276


# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [5]:
# Answer Here
array_4d = np.random.randint(0, 10, size=(2,3,4,5))
print(array_4d)

[[[[0 2 5 6 2]
   [5 1 7 5 1]
   [7 9 3 0 6]
   [1 2 7 1 2]]

  [[2 0 4 6 0]
   [8 5 1 6 6]
   [7 4 1 5 0]
   [0 0 0 8 6]]

  [[6 8 1 8 7]
   [0 0 7 0 9]
   [9 6 1 2 7]
   [4 1 6 3 7]]]


 [[[6 3 7 6 4]
   [6 9 1 8 5]
   [6 7 3 1 4]
   [8 7 8 7 2]]

  [[6 9 8 1 6]
   [1 8 7 7 3]
   [1 7 1 5 6]
   [9 7 6 8 4]]

  [[1 1 4 5 2]
   [9 3 4 9 6]
   [5 6 3 5 7]
   [8 4 3 7 3]]]]


# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [6]:
# Answer Here
array_4d = np.random.randint(0, 10, size=(2,3,4,5))
mean = np.mean(array_4d, axis=1)
print(mean)

[[[2.33333333 5.         4.66666667 3.66666667 5.66666667]
  [4.33333333 5.66666667 5.         5.66666667 4.33333333]
  [5.         4.         0.66666667 6.33333333 7.33333333]
  [7.33333333 5.         5.         2.         1.66666667]]

 [[1.33333333 1.         5.         5.         4.        ]
  [4.66666667 4.66666667 4.66666667 3.66666667 2.        ]
  [6.         4.33333333 4.         6.33333333 4.66666667]
  [3.66666667 1.         6.66666667 5.66666667 3.        ]]]


# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [9]:

# Answer Here
temps = np.random.rand(7, 24, 60) * 100
average_temps_per_day = temps.mean(axis=(1, 2))
print(average_temps_per_day)

[51.12862141 49.28224646 50.00638988 49.11900447 50.28381559 48.61880205
 50.07828261]


Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [11]:
# Answer Here
reading_array = np.arange(4 * 7 * 24 * 60).reshape(4,7,24,60)
max_reading = np.max(reading_array, axis=(1,2,3))
print(max_reading)

[10079 20159 30239 40319]


# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Inpumt:

In [14]:
# Answer Here
dimensions = np.random.rand(100, 50, 3) * 100
#print(dimensions)
average_dimensions = dimensions.mean(axis=(0, 1))
print(average_dimensions)

[49.67836715 50.42280455 49.74070154]


# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [20]:
# Answer Here
data = np.random.rand(5,6,7) * 100
average_measurement = data.mean(axis=(1,2))
standard_deviation = data.std(axis=(1,2))
minimun_measurement = data.min(axis=(1,2))
max_measurement = data.max(axis=(1,2))
print(average_measurement)
print(standard_deviation)
print(minimun_measurement)
print(max_measurement)

[51.70408213 44.95335388 42.60767038 51.0677137  59.01882286]
[30.07491261 28.49165961 25.52315894 30.91582973 25.18623553]
[2.40179772 0.19852449 2.04596688 1.50984093 5.81511679]
[97.97112271 93.69082781 94.87263683 99.27241957 96.33250277]
