# Problem 1: Reshaping for Image Processing
You are working on an image processing project, and you have a grayscale image represented as a 1D NumPy array **img_data** of size **(m * n)**, where m and n are the dimensions of the image. Write a function **reshape_image(img_data, new_shape)** that takes the original image data and a tuple representing the new shape **(p, q)** of the image. Ensure that the total number of pixels remains unchanged. If it's not possible to reshape without changing the total number of pixels, return **None**.

In [ ]:
# Write your function in this cell

In [4]:
import numpy as np

def reshape_image(img_data, new_shape):
  total_pixels_original = len(img_data)
  total_pixels_new = new_shape[0] * new_shape[1]

  if total_pixels_original != total_pixels_new:
    return None

  reshaped_image = np.reshape(img_data, new_shape)

  return reshaped_image

# Assuming a 3x3 image
img_data = np.arange(9)
print(img_data)
new_shape = (3, 3)

result = reshape_image(img_data, new_shape)
print(result)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Problem 2: Matrix Transpose
You are dealing with a dataset stored as a NumPy array **data_matrix** with dimensions **(m, n)**. Implement a function **transpose_matrix(data_matrix)** that returns the transpose of the given matrix.

In [ ]:
# Write your function in this cell

In [16]:
import numpy as np
#This will work only for 2D arrys
def transpose_matrix(data_matrix):
  rows, columns = data_matrix.shape
  transposed_matrix = np.zeros((columns, rows))

  for i in range(rows):
    for j in range(columns):
      transposed_matrix[j][i] = data_matrix[i][j]

  return transposed_matrix

data_matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed_matrix = transpose_matrix(data_matrix)
print(f"Original array: \n{data_matrix}\n")
print(f"Transposed array: \n{transposed_matrix}\n")

#2nd approach for type of arrays
def transpose_matrix(data_matrix):
    transposed_matrix = np.transpose(data_matrix)
    return transposed_matrix

# 2D array (matrix)
data_matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])
transposed_matrix_2d = transpose_matrix(data_matrix_2d)
print(f"Original 2D array:\n{data_matrix_2d}")
print(f"Transposed 2D array:\n{transposed_matrix_2d}\n")

# 3D array
data_matrix_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
transposed_matrix_3d = transpose_matrix(data_matrix_3d)
print(f"Original 3D array:\n{data_matrix_3d}")
print(f"Transposed 3D array:\n{transposed_matrix_3d}\n")

# 1D array
data_matrix_1d = np.array([1, 2, 3, 4])
transposed_matrix_1d = transpose_matrix(data_matrix_1d)
print(f"Original 1D array:\n{data_matrix_1d}")
print(f"Transposed 1D array (no change for 1D arrays):\n{transposed_matrix_1d}\n")

Original array: 
[[1 2 3]
 [4 5 6]]

Transposed array: 
[[1. 4.]
 [2. 5.]
 [3. 6.]]

Original 2D array:
[[1 2 3]
 [4 5 6]]
Transposed 2D array:
[[1 4]
 [2 5]
 [3 6]]

Original 3D array:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Transposed 3D array:
[[[ 1  5  9]
  [ 3  7 11]]

 [[ 2  6 10]
  [ 4  8 12]]]

Original 1D array:
[1 2 3 4]
Transposed 1D array (no change for 1D arrays):
[1 2 3 4]



# Problem 3: Flattening for Data Processing
You have a 2D array representing data from different sensors. Write a function **flatten_sensor_data(sensor_data)** that takes a 2D NumPy array representing the sensor readings and returns a flattened 1D array.

In [ ]:
# Write your function in this cell

In [19]:
import numpy as np

def flatten_sensor_data(sensor_data):
  flattened_array = sensor_data.flatten()
  return flattened_array

sensor_data = np.array([[10, 20, 30], [40, 50, 60]])
flattened_data = flatten_sensor_data(sensor_data)
print(f"Original Array: \n{sensor_data}\n")
print(f"Flattened Array: \n{flattened_data}\n")

Original Array: 
[[10 20 30]
 [40 50 60]]

Flattened Array: 
[10 20 30 40 50 60]

